import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "./../components/shared/header";
import { Footer } from "./../components/shared/footer";
import 'app/sass/globals.sass';

const font = Roboto({
  weight: ["100", "300", "500", "700"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
